matched_files:
  'general/general.snap':
    sheet: 'system'
    matchs:
      '^\s+(ent\d+|fcs\d+)\s+\S+\s+.*':
        label: 'adapter'
      '^\s+(?:ent\d+|fcs\d+)\s+(\S+)\s+.*':
        label: 'slot'
      '^\s+(?:ent\d+|fcs\d+)\s+\S+\s+(.*)':
        label: 'description'
      'Network Address\.+(\S+)':
        label: 'mac'
      '^systemid\s+IBM,(\S+)':
        label: 'serial'
      '^modelname\s+IBM,(\S+)':
        label: 'model'
  'tcpip/tcpip.snap':
    sheet: 'system'
    matchs:
      '(^en\d+)\s+(\d+)\s+[\d\.]+\s+([\d\.]+)':
        label: 'interface'
      'Media Speed Selected:\s+(.*)':
        label: 'media_selected'
      'Media Speed Running:\s+(.*)':
        label: 'media_running'
      'ETHERNET STATISTICS \((ent\d+)\)':
        label: 'media_adapter'


